// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FraudPredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("trans_date_trans_time"), LoadColumn(0)]
        public string Trans_date_trans_time { get; set; }


        [ColumnName("cc_num"), LoadColumn(1)]
        public float Cc_num { get; set; }


        [ColumnName("amt"), LoadColumn(2)]
        public float Amt { get; set; }


        [ColumnName("first"), LoadColumn(3)]
        public string First { get; set; }


        [ColumnName("trans_distance"), LoadColumn(4)]
        public float Trans_distance { get; set; }


        [ColumnName("is_fraud"), LoadColumn(5)]
        public string Is_fraud { get; set; }


    }
}
