// This file was auto-generated by ML.NET Model Builder. 

using System;
using FraudPredictorML.Model;

namespace FraudPredictorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Trans_date_trans_time = @"2/3/2019",
                Cc_num = 3.569685E+15F,
                Amt = 8.571544E+07F,
                Trans_distance = 5152.628F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Is_fraud with predicted Is_fraud from sample data...\n\n");
            Console.WriteLine($"Trans_date_trans_time: {sampleData.Trans_date_trans_time}");
            Console.WriteLine($"Cc_num: {sampleData.Cc_num}");
            Console.WriteLine($"Amt: {sampleData.Amt}");
            Console.WriteLine($"Trans_distance: {sampleData.Trans_distance}");
            Console.WriteLine($"\n\nPredicted Is_fraud value {predictionResult.Prediction} \nPredicted Is_fraud scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
